apiVersion: v1
data:
  prom_config.yml: |-
    global: {evaluation_interval: 5s, scrape_interval: 5s}

    scrape_configs:
    - job_name: 'Clipper Metrics'

      kubernetes_sd_configs:
      - role: pod

      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_label_ai_clipper_container_label]
        action: keep
        regex: {{cluster_name}}
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_ai_clipper_(metric|model_container)_label
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

kind: ConfigMap
metadata:
  name: prometheus-config-at-{{ cluster_name }}
  labels:
    ai.clipper.container.label: {{ cluster_name }}
    ai.clipper.name: metrics