apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{cluster_name}}-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{cluster_name}}-prometheus
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ namespace }}